from library import buildLibrary, render
from scaler import Scaler, ProportionalScaler
from feature_extractor import FeatureExtractor, Features, visualizeFeatures
from template import TemplateComparisonOldFormula, TemplateComparisonNewFormula
from histogram import VerticalHistogramComparison, HorizontalHistogramComparison, HistogramComparison
from fourier_descriptor import FourierComparison
